name: node_io
description: Like dart:io but with Node
version: 0.0.1
#homepage: https://www.example.com
#author: Anatoly Pulyaevskiy <email@example.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
 node:
  path: ../node

dev_dependencies:
  build_runner:
  build_web_compilers:
    path: ../build/build_web_compilers
  test: ^0.12.0
