name: node_io
description: Like dart:io but with Node.
version: 1.0.0-dev.1.0
#homepage: https://www.example.com
#author: Anatoly Pulyaevskiy <email@example.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
 node_interop:
  git:
    url: git@github.com:pulyaevskiy/node-interop.git
    ref: dart20

dev_dependencies:
  test: ^0.12.0
